# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18bf85635f3a9276d5a1591c52521722c815fe9428f32e9269f8d26b6fa5fae44e858b863158c5f5df5f35a2bc0e602748d92a0b90064d37f2f0c1fe8eee1c30

test:
  secret_key_base: 6614d7d0315b7a007c98ab010d07f1298f80bb99cd736a9023ce05beb83d9d47c63b65c3c868cc703b778f7de04a0d8582dda13d786c622f92d20642d9a755d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
